language: go

go:
  - "1.12"

install:
  # 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.59.0/hugo_0.59.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  # 运行hugo命令
  - hugo

after_script:
  # 部署
  - cd ./public
  - git init
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:master

env:
 global:
   # Github Pages
   - GITHUB_REF: github.com/juzl/juzl.github.io